### ISSUE TITLE
Review module grouping structure

### ISSUE THREAD

**Issue by mstade** [zambezi/fun#1]
Originally written by @gabrielmontagne:

> Some of the function we've been adding to fun have landed on the root of the project, some are grouped under array, object, string folders.
> 
> We should at least review the grouping criteria for these elements---perhaps creating a core folder? 
> Perhaps it's fine as it is.
> 
> But I think this is a good moment (the moment before we actually go live!) to review this.

**Comment by gabrielmontagne** [comment]
This will be flattened out when/if we merge #4

**Comment by mstade** [comment]
Fixed in #4 – excellent work @gabrielmontagne!
